### ISSUE TITLE
Support for godot 4

### ISSUE THREAD

**Issue by adam-dorin** [Calame321/Godot_Auto_GridMap#3]
Hello @Calame321,
Your script is awesome!
I have forked this repo and make some changes to the script in order to support godot4
https://github.com/adventurerlog/Godot_Auto_GridMap/tree/v4-support

If you are open to it please create a new branch in this repo called `v4-support`
That way I can open a new pull request, without overwriting the code on `main` and provide some support for the newest version.
Cheers!

**Comment by Calame321** [comment]
Interesting!
I made the branch `v4-support`.

**Comment by adam-dorin** [comment]
Thank you! 
I created the PR at https://github.com/Calame321/Godot_Auto_GridMap/pull/4
Closing this since anything related to the PR can be discussed there.
